### PR TITLE
extend swag deadline, add swag descriptions

### PR DESCRIPTION
**Pull request by shirgoldbird**
Needs to wait for @migetman9 to update the HTML files in the other repo

### CODE REVIEW

**Review by kitsuta — APPROVED** [review]
LGTM! Let us know when it's ready to merge.

**Comment by RobRuana** [comment]
I have not looked into this very deeply, but I don't think it did the thing you wanted it to do. I'm looking at it right now, trying to figure out how to get the alternate buttons to show up...

screen shot 2017-08-20 at 12 48 34 pm

**Comment by ShevaDas** [comment]
Oh noooo! Sorry for not testing my code. 😓 Lmk if I can help reformat or
anything.

**Comment by RobRuana** [comment]
Please don't apologize! I am as bewildered as you are!

**Comment by RobRuana** [comment]
Okay, couple things. First, I added some missing icons (see [this commit](https://github.com/magfest/magwest/commit/d0fae33929bafa7a77bb30fafd164f3d39517ec7)). Second, the prereg page is profoundly confusing. It is rendering the buttons/links as you desire, but it is not making them visible.

I've been trying to divine the difference between the west config and the prime or labs config. I have yet to arrive at any conclusions. This may be a job for @kitsuta.

**Comment by kitsuta** [comment]
Oh dear, I'm not sure why it wouldn't have done that either. :( It looks like it's all good now on the at-door page, but we'll want to audit this later -- I'm not super clear on what it was supposed to be doing vs what it was doing.

**Pull request merged**
