### PR TITLE
Puppetizes prereg_confirm_email_enabled

### PR DESCRIPTION
**Pull request by RobRuana**

### CODE REVIEW

**Review by kitsuta — COMMENTED** [review]
This is good, but I'm going to assume that all MAGFest events want to confirm the email address. Is it possible to make this change in https://github.com/magfest/production-config/blob/master/common.yaml instead?

If you don't think that's necessary, this is totally fine as-is, +1!

**Comment by RobRuana** [comment]
I personally do not like this feature, which is why I only enabled it for prime. I have solicited feedback on slack. If more people want it than don't then I'll change it in common.yaml instead.

**Comment by kitsuta** [comment]
Ah! My bad, I had no idea. We should talk about it if you don't think it's a good idea!

**Comment by RobRuana** [comment]
Nah, I think I am the lone voice on this one. Everyone seems to think it's a good idea, so I moved it to common.yaml.

**Pull request merged**
