### PR TITLE
add magwest specific ssl certs

### PR DESCRIPTION
**Pull request by binary1230**
these go with some certs generated on mcp

### CODE REVIEW

**Review by RobRuana — APPROVED** [review]
+1!

**Comment by kitsuta** [comment]
Does this need to be merged?

**Comment by RobRuana** [comment]
I think at this point its moot.

**Comment by binary1230** [comment]
hm... never got merged eh, guess no one was using the API : )

this can still get merged as it's useful for next year

**Comment by binary1230** [comment]
would still say go ahead and merge this

**Pull request merged**
