### PR TITLE
Remove references to badges as a keepsake

### PR DESCRIPTION
**Pull request by DataFighter**
in Supporter and Vampire donation tiers

We are doing this as supporters do not get extra badges

### CODE REVIEW

**Comment by EmillerOpenwhere** [comment]
Still testing this.

**Comment by EmillerOpenwhere** [comment]
So I would hold off on a merge

**Comment by DataFighter** [comment]
Still testing so I would hold off on a merge.

**Comment by kitsuta** [comment]
While it's great to test stuff, this is a simple enough change that I'm okay with merging it as-is.

**Pull request merged**
