### PR TITLE
Changes Starship Horizons to Escape Room

### PR DESCRIPTION
**Pull request by bds002**

### CODE REVIEW

**Comment by EliAndrewC** [comment]
This will cause there to be 2 different departments both marked as "Escape Room".  Is that what we want?

**Comment by bds002** [comment]
No, we only want 1, I think the 1 is the Deparment name, the other (Location) is the name on the Schedule.

**Comment by kitsuta** [comment]
I think the confusing thing here might be that one of these variables is named `bridge_simulator` and one is named `horizons`. I'm not totally sure what this will do, though I think it will be okay.

**Comment by EliAndrewC** [comment]
> No, we only want 1, I think the 1 is the Deparment name, the other (Location) is the name on the Schedule.

Whoops, you're right!  I hadn't noticed that due to the default formatting on the "Files Changed" tab.

+1 on this.  (Different variable names for the two is probably just a historical artifact and changing that is outside the scope of this PR.)

**Pull request merged**
