### PR TITLE
Fixes magwest #10: Prunes nonexistent departments from magest

### PR DESCRIPTION
**Pull request by RobRuana**
See: https://github.com/magfest/magwest/issues/10

Per Sheva and Dare (migetman9) the following departments are removed:
Autographs
Challenges
Escape Room
Events
Games on Film
LARP
MAGES
MAGFest Grand Championship
Museum
Public Safety
Simulations
Staff Suite
Tabletop (CCG)
Tabletop (DDAL)
Tabletop (Pathfinder)
Yetee Staff
Zombie Tag

### CODE REVIEW

**Comment by kitsuta** [comment]
It looks like you just removed the interests, not the locations themselves. So the 'assigned' checkgroup will still be massive.

**Comment by RobRuana** [comment]
Please forgive my unfamiliarity with the system. I see two possibly relevant config settings:
```
uber::config::job_interests:
```
and
```
uber::config::job_locations:
```

Which should I be modifying?

**Comment by kitsuta** [comment]
Usually, both!

"Job interests" controls the "Where do you want to work?" checkgroup, which is displayed both in the admin form and the pre-reg page. It indicates what departments someone would _like_ to work in.

"Job locations" controls the "Assigned" and "Trusted" checkgroups, and also controls the dropdown of departments in our Jobs page. So it maps to the actual departments.

You'll also often find things in "job locations" that aren't in "job interests" -- departments that need to exist, but don't want to advertise themselves because they already have a full complement of staff (or are contractors).

**Comment by kitsuta** [comment]
Also, whoops, you WERE removing things from `job_locations`. CARRY ON

**Pull request merged**
