### PR TITLE
MAGStock 7: Change badge price back to $50

### PR DESCRIPTION
**Pull request by Hachi05**
Please merge after 0000 EDT, 30 May 17 <3 <3

### CODE REVIEW

**Comment by kitsuta** [comment]
The problem with the way we're doing this flash sale is that the system calculates the badge price of an attendee based on their registered date... _and does not store the price itself_. It merely stores the registered date and simply recalculates based on the registered date.

You already saw what that meant when you made the first change -- people's badge prices were retroactively reduced to $40. That's not a huge deal, I don't think. But if you just change it back, then people who bought the discounted badge will have their badge price updated to $50 -- and if they view their confirmation page, the system will ask them for money!

We ran into this for bucket-based pricing in MAGPrime. We had a stopgap fix, but it was a stopgap and thus removed.

Instead, what you'll want to do is insert the dates and their correct prices. Just because we raise badge prices by convention doesn't mean it has to be this way -- and iirc, I made sure it worked the other way around last year because we needed the badge price to go down over the weekend.

So what you'll want to do is change this:
```
attendee:
     '2017-06-01': 60
     '2017-06-16': 70
```

into something like this:
```
attendee:
     '2017-05-28': 40
     '2017-05-30': 50
     '2017-06-01': 60
     '2017-06-16': 70
```

**Comment by Hachi05** [comment]
What about badges bought before the 28th? What should I make
uber::config::initial_attendee, still 40?

Thanks!

**Comment by Hachi05** [comment]
Corrected with your suggestions. Also fixed date for At-Door price.

**Comment by kitsuta** [comment]
Yeah, initial_attendee would be $50 assuming you wanted badges bought before the 28th to be $50.

With this, we should actually be able to merge and deploy this and have the prices update automatically. :)

**Pull request merged**
