### PR TITLE
Job Descriptions updated

### PR DESCRIPTION
**Pull request by bds002**
From MAGStock planning meeting, removing Cat herding from an option for general volunteers, keeping it an assignment for Admin staff.
Changing Standby/Misc to General Support.
Added to Events to event calendar - Concerts, Events, Slip -n- Slide 
(Slip n side is a multi-day event with multiple hours.... VS events that will have a set time).

### CODE REVIEW

**Comment by EliAndrewC** [comment]
+1

**Comment by binary1230** [comment]
does removing or adding things from this list have any side effects of confusing things in the DB? or does it not matter since we haven't scheduled/shifted/jobs'd anything against them yet?

**Comment by bds002** [comment]
? The answer to the first part is that we have done this on the fly in the past.... changes names, reordered departments etc....  For the second question - We have created shifts in some departments already... that's actually my job to get done ;) and some of the other DH's have created shifts as well. 

- I'm not sure how it affects the Schedule - Events Calendar is currently blank.

**Comment by EliAndrewC** [comment]
> does removing or adding things from this list have any side effects of confusing things in the DB? or does it not matter since we haven't scheduled/shifted/jobs'd anything against them yet?

To give a more authoritative answer: it won't affect anything in this case since as Brent noted the schedule is currently blank.  As currently programmed, it would give an exception if you removed a config option which was currently being used on the schedule.

**Pull request merged**
