### PR TITLE
Update LAN locations.

### PR DESCRIPTION
**Pull request by cmchick**
LAN only has one theater now.

### CODE REVIEW

**Review by RobRuana — APPROVED** [review]
+1!

**Comment by kitsuta** [comment]
Did this... actually remove the location in question? Don't we need to kick the DB to remove existing rooms on the schedule?

**Comment by RobRuana** [comment]
I think as long as no events have referenced the deleted room we're okay (which they didn't).

**Comment by kitsuta** [comment]
Huh, well, as long as the room got deleted from the schedule (and I can see now that it did)!

**Pull request merged**
