### PR TITLE
Minor ribbon/wristband text adjust

### PR DESCRIPTION
**Pull request by nickthenewbie1**
Changed the text label of the under_13 ribbon/wristband checkbox to reflect what the physical wristband actually has printed on it

### CODE REVIEW

**Review by RobRuana — APPROVED** [review]
+1!

**Comment by kitsuta** [comment]
For the record, I totally think the wristbands should say "under 13" :P

**Comment by RobRuana** [comment]
"Under 13" is technically more accurate. Someone is only 12 years old at an instantaneous point in spacetime. Thereafter they are 12 years plus some amount of time, like 12 years and 1 second, or 12 years and 3 months.

However, "Under 13" is probably more easily confused by the general public, because it includes the actual number "13". Without putting much thought into it, someone could easily glance at the phrase, see that it includes the number "13", and conclude that 13 year olds are included in the category.

As a side note, this is another case where we would benefit from automatically calculated ribbons (in this case calculated from the attendee's birthdate).

**Comment by kitsuta** [comment]
We do actually automatically calculate that ribbon, it's just in the `magprime` repo. :)

**Pull request merged**
